buildCommand: "cd EduPayAfrica && pip install -r ../requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
startCommand: "cd EduPayAfrica && gunicorn EduPayAfrica.wsgi:application"